# Source: cluster-api-aws/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cc4ebx2rw-capi-aws
  namespace: cc4ebx2rw
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cc4ebx2rw-capi-aws
subjects:
- kind: ServiceAccount
  name: cc4ebx2rw-capi-aws
